### ISSUE TITLE
When I entered the correct account password to log in, it still jumped back to the login page

### ISSUE THREAD

**Issue by zhangzp-handsome** [spring-projects-experimental/spring-authorization-server#255]
**Describe the bug**
I modified the sample code, removed OIDC related parts, and only kept the authorization code part. After running the program, input the correct account password, but still redirected to the login page.

**To Reproduce**
Firstly, i changed the 'application.yml' and 'SecurityConfig.java' in the client code.

_application.yml_

```
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.boot.autoconfigure: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/messaging-client-authorization-code"
            scope: message.read,message.write,message.superman
            client-name: messaging-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000

messages:
  base-uri: http://localhost:8090/messages
```

_SecurityConfig.java_

```java
/**
 * @author Joe Grandja
 * @since 0.0.1
 */
@EnableWebSecurity
public class SecurityConfig {

    @Bean
    WebSecurityCustomizer webSecurityCustomizer() {
        return (web) -> web.ignoring().antMatchers("/webjars/**");
    }

    @Bean
    SecurityFilterChain securityFilterChain(HttpSecurity http) throws Exception {
        http.authorizeRequests(authorizeRequests ->
                authorizeRequests.anyRequest().authenticated())
                .oauth2Login(oauth2Login ->
                        oauth2Login.loginPage("/oauth2/authorization/messaging-client-authorization-code"))
                .oauth2Client(withDefaults());
        return http.build();
    }
}
```

Secondly, i changes 'AuthorizationServerConfig.java' in the server code. 

```java

/**
 * @author Joe Grandja
 * @since 0.0.1
 */
@Configuration(proxyBeanMethods = false)
@Import(OAuth2AuthorizationServerConfiguration.class)
public class AuthorizationServerConfig {
    @Bean
    public RegisteredClientRepository registeredClientRepository() {
        RegisteredClient registeredClient = getRegisteredClientOnlyAuthorizationCode();
        return new InMemoryRegisteredClientRepository(registeredClient);
    }
    
    private RegisteredClient getRegisteredClientOnlyAuthorizationCode() {
        return RegisteredClient
                .withId("OnlyCode" + UUID.randomUUID().toString())
                .clientId("messaging-client")
                .clientSecret("secret")
                .clientAuthenticationMethod(ClientAuthenticationMethod.BASIC)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .authorizationGrantType(AuthorizationGrantType.REFRESH_TOKEN)
                .redirectUri("http://localhost:8080/login/oauth2/code/messaging-client-authorization-code")
                .scope("message.read")
                .scope("message.write")
                .scope("message.superman")
                .clientSettings(clientSettings -> clientSettings.requireUserConsent(false))
                .build();
    }

  
    @Bean
    public JWKSource<SecurityContext> jwkSource() {
        RSAKey rsaKey = Jwks.generateRsa();
        JWKSet jwkSet = new JWKSet(rsaKey);
        return (jwkSelector, securityContext) -> jwkSelector.select(jwkSet);
    }
    
    @Bean
    public ProviderSettings providerSettings() {
        //Sets the URL the Provider uses as its Issuer Identifier.
        return new ProviderSettings().issuer("http://auth-server:9000");
    }
}


```
**Expected behavior**
I hope to jump to index.html after inputting the correct account password, but after inputting, it is still the login page.Did I make a mistake in the configuration of the client side or the server side?
